#!/bin/bash
# vim: set ft=sh

set -e -x

export GOPATH=$PWD
export PATH=$PWD/bin:$PATH

export ROOT_DIR=$PWD

cd src/code.cloudfoundry.org/garden-performance-acceptance-tests
ginkgo -nodes=1 "$@" | tee output.txt

tail -n 15 output.txt | grep Time > $ROOT_DIR/stats/stats.txt
